name: Publish snapshots

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish with gradlew
        run: ./gradlew -Psnapshot :toolargetool:publishReleasePublicationToSonatypeRepository